/**
 * bunq assignment
 * frontend for assignment.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: praneethmendu@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface User { 
    id?: number;
    name?: string;
}

export interface UserList { 
    users?: string;
    name?: string;
}